### ISSUE TITLE
Best way to create bibliography

### ISSUE THREAD

**Issue by RicGomez** [umasscs/umassthesis#17]
My school requires APA style for references and bibliography. I usually use Biblatex to do this. However, I'm having problems using biblatex with the umthesis class.

What is the best way to process references with umthesis? 

thanks.

**Comment by jvilk** [comment]
As the current maintainer of the style file, I'm cleaning out old issues. Since this issue appears (to me) to be an issue with a particular LaTeX setup and has been dormant for some time now, I am closing it for now.

Feel free to reopen if you continue to have difficulties with the style file.
