### ISSUE TITLE
Date not appearing in all caps in abstract

### ISSUE THREAD

**Issue by ssclark** [umasscs/umassthesis#19]
I submitted my thesis for review and the grad school got back to me saying that the date which appears in the abstract heading must be in all caps --- for example, SEPTEMBER 2013 rather than September 2013.

I found the offending code at line 143 in umthsd.clo:

\uppercase\expandafter{@date} \par

The problem seems to be that \uppercase does not work correctly in conjunction with \expandafter. For my thesis, I just replaced \@date with "SEPTEMBER 2013", but that is obviously not a general solution.

**Comment by jvilk** [comment]
Hello! I am the new maintainer of the style file. The date is appropriately capitalized for the example thesis in the repository, so I'm considering this bug to be fixed.
