### ISSUE TITLE
Rename the class?

### ISSUE THREAD

**Issue by denkav** [umasscs/umassthesis#22]
This is a minor issue, but easy enough to fix if there isn't a compelling reason not to. The name of this class is the same as the UMichigan thesis class which is [hosted on CTAN](http://www.ctan.org/tex-archive/macros/latex/contrib/umthesis) and included in the TeXLive and MikTeX distributions.

I have had a number of novice users not realize this conflict and express utter confusion when after installing the UMass class they were unable to invoke it.

Is there any reason not to rename the class in order to avoid this conflict?

**Comment by perimosocordiae** [comment]
@ransford: The last thing to do before closing this issue is to rename the repo. Github will redirect all the links to the old name automatically, so there isn't much danger in doing so.

Once you do that, I'll update the UMass internal docs.

**Comment by ransford** [comment]
Done!

(@perimosocordiae I just made you an "owner" of the umasscs group -- can you find one or two other people in the department to add as owners, then remove my owner-level access?)

**Comment by perimosocordiae** [comment]
Thanks! I'll scout around at the next grad elections.
