### ISSUE TITLE
Adding Glossaries/List of Abbreviations

### ISSUE THREAD

**Issue by palumr** [umasscs/umassthesis#24]
This isn't an issue, but I've added a list of abbreviations/glossaries to my dissertation with this package, so figured I'd post the how-to here so others can find it easily. If there's a better forum for advice on using this, let me know.

I'm using the [glossaries](https://www.ctan.org/pkg/glossaries) package. See the following sample for a List of Abbreviations (sorry, I don't have time to write a MWE right now).

    \documentclass[dissertation]{umassthesis}
    
    ...
    
    \usepackage[toc,acronym,xindy,section=chapter,numberedsection=autolabel]{glossaries}

    ...

    % sample acronym
    \newacronym{umass}{UMass}{University of Massachusetts}
    % make the glossary
    \makeglossaries

    ...

    \begin{document}
    
    ...
    
    \tableofcontents                	% Table of contents
    \listoftables                   	% List of Tables
    \listoffigures                  	% List of Figures
    \printglossary[type=\acronymtype,title=List of Abbreviations,toctitle=List of Abbreviations] 
    
    ...
    
    This is an abbreviation for \gls{umass}.

    \end{document}

Hope this helps anyone. cheers.

**Comment by ransford** [comment]
Maybe @perimosocordiae wants to add this to the example -- might not be too hard.  Regardless, thanks @palumr!
