### ISSUE TITLE
Making and index

### ISSUE THREAD

**Issue by RicGomez** [umasscs/umassthesis#7]
Hello, 

I know this is not required by the Grad School, but I want to create a version of my dissertation with and index

I'm using the lines below in the preamble of my .tex file: 

\usepackage{makeidx}
\usepackage{showidx}
\makeindex

with \index{key} in the text to indicate the words I want to use in the index

and \printindex at the end of the document

However, when I compile the .tex file the index appears in the Abstract page, on the margin

Not sure if this is important, but I'm using MikTex 2.9 and TexnicCenter

any help is greatly appreciated.

**Comment by jvilk** [comment]
As this problem appears to be dormant, I am closing it for now. Let me know if you continue to have issues.
