### ISSUE TITLE
working with minitoc

### ISSUE THREAD

**Issue by RicGomez** [umasscs/umassthesis#9]
My dissertation includes a chapter that is a report of small scale research. I want to create a table of contents for this specific chapter. I've tried minitoc but the build crashes when \usepackage{minitoc} is invoked...any thoughts how I can get around this? Cheers

**Comment by jvilk** [comment]
I'm closing this issue for now. Let me know if you want further support with it. It would be easiest if you could supply a LaTeX file that demonstrates the issue.
